version: 2
updates:
  # Devcontainers
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
  
  # Root npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
  
  # Backend npm dependencies
  - package-ecosystem: "npm"
    directory: "/diamondz-playhouse/backend"
    schedule:
      interval: weekly
  
  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/diamondz-playhouse/frontend"
    schedule:
      interval: weekly