version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/diamondz-playhouse/backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/diamondz-playhouse/frontend"
    schedule:
      interval: "weekly"